/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author john Emjay
 */
public class Navigation extends javax.swing.JFrame {
    private int sectionId;
    private javax.swing.JLabel headerLabel;

    /**
     * Creates new form Navigation
     */
    public Navigation(int sectionId) {
        this.sectionId = sectionId;
        initComponents();
        setupHeaderLabel();
        setSectionTitle();
    }

    private void setupHeaderLabel() {
        headerLabel = new javax.swing.JLabel();
        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 24));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setForeground(new java.awt.Color(0, 0, 0));

        // Add the header label to the top of the content pane
        javax.swing.JPanel headerPanel = (javax.swing.JPanel) getContentPane().getComponent(0);
        headerPanel.add(headerLabel, java.awt.BorderLayout.CENTER);

        // Update header text based on section
        if (sectionId == -1) {
            headerLabel.setText("Navigation");
            return;
        }

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crms", "root", "");
            String query = "SELECT section_name, section_code FROM sections WHERE section_id = ?";
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setInt(1, sectionId);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                String sectionName = rs.getString("section_name");
                String sectionCode = rs.getString("section_code");
                headerLabel.setText("Section " + sectionCode + " - " + sectionName);
            }

            rs.close();
            pstmt.close();
            con.close();
        } catch (SQLException e) {
            headerLabel.setText("Section " + sectionId);
            e.printStackTrace();
        }
    }

    private void setSectionTitle() {
        if (sectionId == -1) {
            setTitle("Navigation");
            return;
        }

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crms", "root", "");
            String query = "SELECT section_name, section_code FROM sections WHERE section_id = ?";
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setInt(1, sectionId);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                String sectionName = rs.getString("section_name");
                String sectionCode = rs.getString("section_code");
                setTitle("Section " + sectionCode + " - " + sectionName);
            }

            rs.close();
            pstmt.close();
            con.close();
        } catch (SQLException e) {
            setTitle("Section " + sectionId);
            e.printStackTrace();
        }
    }

    // Keep the default constructor for backward compatibility
    public Navigation() {
        this(-1); // Use -1 or another sentinel value to indicate no section selected
    }

    public int getSectionId() {
        return this.sectionId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new java.awt.BorderLayout()); // Set BorderLayout
        
        // Create a panel for the header with some padding
        javax.swing.JPanel headerPanel = new javax.swing.JPanel();
        headerPanel.setLayout(new java.awt.BorderLayout());
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        
        // Create main content panel
        javax.swing.JPanel contentPanel = new javax.swing.JPanel();
        
        rojeru_san.complementos.RSButtonHover btnClasswork_Home = new rojeru_san.complementos.RSButtonHover();
        rojeru_san.complementos.RSButtonHover btnStudents_Home = new rojeru_san.complementos.RSButtonHover();
        javax.swing.JButton jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClasswork_Home.setBackground(new java.awt.Color(255, 255, 255));
        btnClasswork_Home.setForeground(new java.awt.Color(0, 0, 0));
        btnClasswork_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Classwork.png"))); // NOI18N
        btnClasswork_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasswork_HomeActionPerformed(evt);
            }
        });

        btnStudents_Home.setBackground(new java.awt.Color(255, 255, 255));
        btnStudents_Home.setForeground(new java.awt.Color(0, 0, 0));
        btnStudents_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Students.png"))); // NOI18N
        btnStudents_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudents_HomeActionPerformed(evt);
            }
        });

        jButton1.setText("Grades");
        
        // Add components to the content panel
        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnStudents_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnClasswork_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudents_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClasswork_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        
        // Add panels to the frame
        add(headerPanel, java.awt.BorderLayout.NORTH);
        add(contentPanel, java.awt.BorderLayout.CENTER);
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClasswork_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasswork_HomeActionPerformed
        Classwork classworkFrame = new Classwork(sectionId);
        classworkFrame.setLocationRelativeTo(this);
        classworkFrame.setVisible(true);
    }//GEN-LAST:event_btnClasswork_HomeActionPerformed

    private void btnStudents_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudents_HomeActionPerformed
        Students studentsFrame = new Students(sectionId);
        studentsFrame.setLocationRelativeTo(this);
        studentsFrame.setVisible(true);
    }//GEN-LAST:event_btnStudents_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Navigation(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
